### ISSUE TITLE
Skip strategy and RecyclerView scroll position

### ISSUE THREAD

**Issue by nickilanjelo** [moxy-community/Moxy#83]
Hi!

I have a problem with saving RecyclerView scroll position - every time when screen rotates RecyclerView recreates and looses scroll. This problem appears only with Fragments. Project with Activity works well. Sample project here: [https://github.com/nickilanjelo/MoxySkipIssue](url)

**Comment by alaershov** [comment]
Your link is broken if you click on it. We'll check your issue, thanks.

**Comment by nickilanjelo** [comment]
Sorry, try this link:
https://github.com/nickilanjelo/MoxySkipIssue/

**Comment by alaershov** [comment]
First of all, you use Moxy a bit wrong. Let's see what happens:
1) The fragment is created by the Nav component.
2) `Fragment.onStart()` is called
3) You call `testPresenter.getStrings()` from onStart()
4) Presenter calls `showList()`

In other words, you refresh the list each time the screen is rotated, because you do it from onStart.

Skip strategy does not prevent the View method from being called twice if you call it twice yourself. It's used in cases when you don't want to call the method on the View if the Presenter called ViewState method when the View was not attached.

And all of this is unrelated to scroll position preservation in RecyclerView :) You should research the correct way to do it, and try to see if it works without Moxy. Then use Moxy and tell me if there are any problems. Good luck!

**Comment by nickilanjelo** [comment]
I tried to make it without Moxy and call showList method in OnViewCreated callback:
`override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        showList(DataProvider.getData())
    }`
Everything works fine and scroll position stay normally, but when I call presenter from this callback - RecyclerView refresh scroll again. I'll upload this version.
I understand that onViewCreated calls every time when screen rotates, but I don't understand why it works with presenter another way.

**Comment by alaershov** [comment]
It turned out to be a cool issue) Here goes the explanation.

We have a problem:

- call with presenter `testPresenter.getStrings()` **does not** restore scroll position
- call with no presenter `showList(...)` **does** restore scroll position

The reason is quite simple: lifecycle.

You see, in Moxy, when Presenter calls `viewState.showList(...)`, the actual View method implementation is not called immediately. Instead, you call the ViewState method, and the point of ViewState is to wait until the View is attached to Presenter, and execute all pending method calls on the View.

This is what happens with Moxy, if we add some logs:
```
onViewCreated()
presenter.getStrings() <-- this is your call from onViewCreated()
onViewStateRestored() <-- this is where Android restores the scroll position of RecyclerView
before onStart()
before presenter.attachView()
showList(...) <-- this is where ViewState calls actual View method and you set adapter and list to RecyclerView. Scroll position is reset to 0
after presenter.attachView()
after onStart()

SCREEN ROTATED

the same happens again
```
You can see that scroll position is restored before ViewState calls View method and resets scroll to 0.

And this is without Moxy:
```
onViewCreated()
showList(...) <-- this is your call from onViewCreated(), you set adapter and list to RecyclerView. Scroll position is reset to 0
onViewStateRestored() <-- this is where Android restores the scroll position of RecyclerView
before onStart()
before presenter.attachView()
after presenter.attachView()
after onStart()

SCREEN ROTATED

the same happens again
```
Note that in that case showList() is called immediately from onViewCreated and after that Android restores scroll position.

Hope the underlying issue is clear for you now.

**Comment by nickilanjelo** [comment]
Thank for great explanation!

Do you have any ideas how to handle this situation in MVP?
I think that using only fragment without presenter is a bad approach :(

**Comment by nickilanjelo** [comment]
Sorry, this wasn't Moxy feature :)
This happens only when you set layoutManager for RecyclerView from wrong lifecycle callback. This should happen in 'ASAP' callback (onViewCreated, onCreate) or in layout xml.

**Comment by alaershov** [comment]
Cool, thanks for taking the time to post a solution!
